### ISSUE TITLE
circular imports or bug?

### ISSUE THREAD

**Issue by paddy10tellys** [talkpython/anvil-course#2]
I am at https://training.talkpython.fm/player/course/anvil-web-apps-with-just-python/lecture/210403 but when I try to run it as at 04:49 / 05:25 I get 

> Error “ImportError: No module named navigation”

this post is relevant - the anvil devs suggest circualr imports or a bug
https://anvil.works/forum/t/import-client-module-error/3926/10

**Comment by mikeckennedy** [comment]
Hi @paddy10tellys I don't think that's the issue. The Anvil folks have changed the layout of files affecting the import statements since we recording the videos (a month or so ago?). So you'll need to import from the `project_name.module_name`. For example, see this screenshot:

<img width="742" alt="Screen Shot 2020-02-24 at 1 24 04 PM" src="https://user-images.githubusercontent.com/2035561/75192447-19f48980-5709-11ea-9f6a-9629a210b467.png">

**Comment by paddy10tellys** [comment]
Thanks @mikeckennedy - when I tried that I got this:

> ValueError: Attempted relative import beyond toplevel package
at navigation, line 1
  called from HomeForm, line 3 

The anvil.works autocomplete feature now offers  `.. component` rather than just `component` when writing import statements suggesting the directory structure isn't what it was when you wrote your code?

here are my the two files
 # navigation
```
from ..AddMeasurementComponent import AddMeasurementComponent # from module import class
from ..HomeAnonComponent import HomeAnonComponent
from ..CompareComponent import CompareComponent
from ..AccountComponent import AccountComponent
from ..HomeDetailsComponent import HomeDetailsComponent
from ..SetHeightComponent import SetHeightComponent

home_form = None

def get_form():
  if home_form is None:
    raise Exception("You must set the home form first!")
    
  return home_form

def go_add():   
    form = get_form()
    form.load_component(AddMeasurementComponent)
    #inline the AddMeasurementComponent constructor as the argument to form.load_component()
    
def go_home():
  form = get_form()
  form.load_component(HomeAnonComponent)
 
def go_compare():
  form = get_form()
  form.load_component(CompareComponent)
  
def go_account():
  form = get_form()
  form.load_component(AccountComponent)
 ``` 



# HomeForm
```
from ._anvil_designer import HomeFormTemplate
 from anvil import *
 import Endovelicus.navigation


class HomeForm(HomeFormTemplate):
  def __init__(self, **properties):
    # Set Form properties and Data Bindings.
    self.init_components(**properties)
    
    navigation.home_form = self
    navigation.go_home()
    # Any code you write here will run when the form opens.  
    
  def add_click(self, **event_args):
    navigation.go_add()

  def link_home_click(self, **event_args):
    navigation.go_home()

  def link_compare_click(self, **event_args):
    navigation.go_compare()

  def account_click(self, **event_args):
    navigation.go_account()
  
  def register_click(self, **event_args):
    pass
  
  def login_click(self, **event_args):
   pass

  def logout_click(self, **event_args):
    pass   

  def load_component(self, cmpt):
    self.column_panel_content.clear()  # clears current content from column_panel_content
    self.column_panel_content.add_component(cmpt)  # adds new component to column_panel_content
 ```

**Comment by mikeckennedy** [comment]
Hi,

Sounds like it might not be a proper package or something? This is not what I wrote, what I wrote was:

```
# No .. :)
from HomeAnonComponent import HomeAnonComponent
```

But they changed it so it should work with `from projectname.HomeAnonComponent import HomeAnonComponent`

Best,
Michael

**Comment by s-cork** [comment]
Hi @mikeckennedy  - a quick fix for the change in package styles...

If you share an old blank app for your users to clone and make a quick amendment video to explain that they should start from the clone rather than a creating a new blank app... This way your users won't need to worry about new style packaged forms looking different to you're video lectures! which are great btw! 

They just need to make sure they don't hit ⭐️ enable packages/upgrade to python 3. 
(And if they do by accident they can always just revert back to a version before they changed it)

This way they can have Anvil as it was before the upgrade since old-style forms are still supported.

Here's an old blank clone if you don't have one... 
https://anvil.works/build#clone:3QU4NLGDEYACNATO=JR45EFFLJZKZOIAMWTI73FD5

**Comment by paddy10tellys** [comment]
build it and they will come...

Hell, I'll buy it!!!
